import type { Metadata } from 'next';
import './globals.css';
import Sidebar from '@/components/sidebar/sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='min-h-screen'>
      <body className='min-h-screen'>
        <div className='flex space-x-5 min-h-screen bg-sky-50'>
          <Sidebar />
          <main className='p-5 w-full'>{children}</main>
        </div>
      </body>
    </html>
  );
}
